name: Update Spec with Latest Monado Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm rpm2cpio cpio
          sudo apt-get install -y python3-setuptools
          # Install rpmdevtools from source (no apt package)
          git clone https://src.fedoraproject.org/rpms/rpmdevtools.git
          cd rpmdevtools
          mkdir -p ~/bin
          cp rpmdev-bumpspec ~/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Get latest Monado commit
        id: monado
        run: |
          latest_commit=$(git ls-remote https://gitlab.freedesktop.org/monado/monado.git HEAD | cut -c1-7)
          echo "commit=$latest_commit" >> "$GITHUB_OUTPUT"

      - name: Get current commit from spec file
        id: current
        run: |
          current_commit=$(grep '^%global commit' *.spec | awk '{ print $3 }')
          echo "current=$current_commit" >> "$GITHUB_OUTPUT"

      - name: Check if update is needed
        id: check
        run: |
          if [ "${{ steps.monado.outputs.commit }}" = "${{ steps.current.outputs.current }}" ]; then
            echo "No new commit. Exiting gracefully."
            echo "update_needed=false" >> "$GITHUB_OUTPUT"
          else
            echo "New commit detected."
            echo "update_needed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit early if no update is needed
        if: steps.check.outputs.update_needed == 'false'
        run: |
          echo "Spec is already up to date with commit ${{ steps.current.outputs.current }}"
          exit 0

      - name: Generate version string
        if: steps.check.outputs.update_needed == 'true'
        id: version
        run: |
          timestamp=$(date -u +'%Y%m%d%H%M')
          echo "version=${timestamp}${{ steps.monado.outputs.commit }}" >> "$GITHUB_OUTPUT"

      - name: Update spec file with new version/commit
        if: steps.check.outputs.update_needed == 'true'
        run: |
          sed -i -E "s|^%global commit .*|%global commit ${{ steps.monado.outputs.commit }}|" *.spec
          sed -i -E "s|^%global datetimever .*|%global datetimever ${{ steps.version.outputs.version }}|" *.spec
          sed -i -E "s|^(Version:\s*).*|\1%{datetimever}|" *.spec

      - name: Update changelog
        if: steps.check.outputs.update_needed == 'true'
        run: |
          rpmdev-bumpspec --comment "Auto-update to Monado commit ${{ steps.monado.outputs.commit }}" \
                          --user "GitHub Action <actions@github.com>" *.spec

      - name: Commit and push changes
        if: steps.check.outputs.update_needed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Update spec to Monado commit ${{ steps.monado.outputs.commit }}"
          git push
